<?php echo $this->doctype(); ?>
<html>
    <head>
        <?php echo $this->headTitle('Church Point')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    </head>
    <body>
        Working
        <div>
            <?php echo $this->content; ?>
        </div>
        <div>
            Footer
        </div>
    </body>
</html>